(function(){
  function pct(v){return v==null?'—':Math.round(Number(v)*100)+'%'}
  function num(v,d=2){return v==null?'—':Number(v).toFixed(d)}
  function changes(){let xs=(D.comparison||{}).changes||[];if(!xs.length&&D.candidates?.[0]?.pairs)xs=D.candidates[0].pairs;return xs.filter(x=>x?.out?.id&&x?.in?.id)}
  function replacePlayers(rows,removeKey,addKey,xs){const m=new Map((rows||[]).filter(x=>x?.id!=null).map(x=>[Number(x.id),x]));xs.forEach(ch=>{m.delete(Number(ch[removeKey].id));m.set(Number(ch[addKey].id),ch[addKey])});return [...m.values()]}
  function benchFrom(squad,xi){const ids=new Set((xi||[]).map(x=>Number(x.id)));return (squad||[]).filter(x=>!ids.has(Number(x.id)))}
  function benchCard(p,mode){const red=mode==='out',green=mode==='in';const style=red?'position:relative;border:3px solid #ff496b;background:#ff496b16;box-shadow:0 0 0 2px #4b0714,0 0 22px #ff496b88':green?'position:relative;border:3px solid #18eda0;background:#18eda014;box-shadow:0 0 0 2px #063d2a,0 0 22px #18eda066':'position:relative';const badge=red?'<span style="position:absolute;right:6px;top:6px;padding:3px 7px;border-radius:99px;background:#ff496b;color:#fff;font-size:8px;font-weight:1000;z-index:4">UT</span>':green?'<span style="position:absolute;right:6px;top:6px;padding:3px 7px;border-radius:99px;background:#00a96e;color:#fff;font-size:8px;font-weight:1000;z-index:4">INN</span>':'';return `<div class="benchCard" data-player-id="${p.id}" style="${style}">${badge}${kit(p)}<span class="name">${esc(p.name)}</span><span class="pos">${esc(P[p.position]||p.position||'')}</span><span class="xp">${Number(p.xp||0).toFixed(2)} xP</span><span class="fix">${esc(p.fixture||'')}</span></div>`}
  function squadHealth(rows){const ids=rows.map(x=>Number(x.id)).filter(Boolean),unique=new Set(ids);const pos={GK:0,DEF:0,MID:0,FWD:0};rows.forEach(x=>{if(pos[x.position]!=null)pos[x.position]++});const valid=rows.length===15&&unique.size===15&&pos.GK===2&&pos.DEF===5&&pos.MID===5&&pos.FWD===3;return {valid,count:rows.length,unique:unique.size,pos}}
  function sourceNote(health){const gw=D.source_snapshot_gw;const generated=D.generated_at?new Date(D.generated_at).toLocaleString('no-NO',{dateStyle:'short',timeStyle:'short'}):'—';const ok=health.valid;return `<div id="fplSourceNote" style="margin:8px 0 12px;padding:11px 12px;border-radius:15px;border:1px solid ${ok?'#18eda035':'#ff496b55'};background:${ok?'#18eda009':'#ff496b0d'};font-size:10px;line-height:1.5;color:#ddd4e8"><div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><b style="color:${ok?'#aaffdc':'#ff9aaf'}">${ok?'✓':'!'} Siste bekreftede FPL-lag${gw?' · GW '+gw:''}</b><span style="color:#8e849d">Feed ${generated}</span></div><div style="margin-top:4px;color:#aaa2ba">${ok?`15/15 spillere · ${health.pos.GK} GK · ${health.pos.DEF} DEF · ${health.pos.MID} MID · ${health.pos.FWD} FWD`:'Snapshotet består ikke lagkontrollen og bør ikke behandles som et komplett FPL-lag.'}</div></div>`}
  function deadlineBox(){if(!D.deadline_time||document.querySelector('#deadlinePulse'))return;const dl=new Date(D.deadline_time),now=new Date(),hrs=(dl-now)/36e5;const urgent=hrs>=0&&hrs<24;const text=hrs<0?'Deadline passert':hrs<24?`${Math.max(0,Math.floor(hrs))}t ${Math.max(0,Math.floor((hrs%1)*60))}m til deadline`:dl.toLocaleString('no-NO',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});const host=document.querySelector('#meta')?.parentElement||document.querySelector('.hero');if(host)host.insertAdjacentHTML('beforeend',`<div id="deadlinePulse" style="margin-top:8px;display:inline-flex;align-items:center;gap:7px;padding:6px 10px;border-radius:99px;border:1px solid ${urgent?'#ffd45b55':'#ffffff18'};background:${urgent?'#ffd45b10':'#ffffff08'};font-size:10px;font-weight:800;color:${urgent?'#ffe39a':'#cfc7da'}"><span style="width:7px;height:7px;border-radius:50%;background:${urgent?'#ffd45b':'#18eda0'}"></span>${text}</div>`)}
  function insightBar(){if(document.querySelector('#squadInsights'))return;const host=document.querySelector('#current')?.closest('.section');if(!host)return;const xi=(D.comparison||{}).current_xi||D.lineup||[];const total=xi.reduce((s,p)=>s+Number(p.xp||0),0);const risky=xi.filter(p=>Number(p.availability??1)<.85||Number(p.expected_minutes??90)<65).length;const hard=xi.filter(p=>String(p.risk||'').toLowerCase()==='høy').length;const cap=xi.find(p=>p.captain)||{};host.insertAdjacentHTML('beforebegin',`<div id="squadInsights" class="section" style="padding:11px 12px"><div style="display:grid;grid-template-columns:repeat(4,1fr);gap:7px;text-align:center"><div><b>${total.toFixed(1)}</b><span class="muted" style="display:block;font-size:8px">XI xP</span></div><div><b>${risky}</b><span class="muted" style="display:block;font-size:8px">minutt/availability-varsel</span></div><div><b>${hard}</b><span class="muted" style="display:block;font-size:8px">høy risiko</span></div><div><b>${esc(cap.name||'—')}</b><span class="muted" style="display:block;font-size:8px">kaptein</span></div></div></div>`)}
  function allPlayers(){const m=new Map();[...(D.lineup||[]),...(D.bench||[]),...((D.comparison||{}).current_xi||[]),...((D.comparison||{}).transfer_xi||[])].forEach(p=>{if(p?.id!=null)m.set(Number(p.id),p)});changes().forEach(c=>{m.set(Number(c.out.id),c.out);m.set(Number(c.in.id),c.in)});return m}
  function fdrColor(d){return d<=2?'#18eda0':d===3?'#ffd45b':'#ff647f'}
  function fixtureStrip(p){const fs=(p.fixture_outlook||[]).slice(0,3);if(!fs.length)return '<span style="color:#91879d">Ingen 3-GW-data</span>';return `<span style="display:flex;justify-content:center;gap:3px">${fs.map(f=>`<span title="GW${f.gw} · ${f.xp??0} xP" style="min-width:31px;padding:3px 4px;border-radius:7px;background:${fdrColor(Number(f.difficulty))}22;border:1px solid ${fdrColor(Number(f.difficulty))}55;color:${fdrColor(Number(f.difficulty))};font-size:7px;font-weight:1000;line-height:1.1">${esc(f.label||'—')}<small style="display:block;font-size:6px;opacity:.8">${f.difficulty||'—'}</small></span>`).join('')}</span>`}
  function viewValue(p,mode){if(mode==='fixture')return '';if(mode==='form'){const f=p.form||{};const r=Number(f.recent_multiplier);return Number.isFinite(r)?`Form ${r.toFixed(2)}×`:'Form —'}if(mode==='risk'){const a=Math.round(Number(p.availability??1)*100),m=Math.round(Number(p.expected_minutes??90));return `${String(p.risk||'lav').toUpperCase()} · ${m}m · ${a}%`}return `${Number(p.xp||0).toFixed(2)} xP`}
  function applySquadView(mode){localStorage.setItem('fplSquadView',mode);document.querySelectorAll('#squadViewSelector button').forEach(b=>{const on=b.dataset.mode===mode;b.style.background=on?'#18eda018':'transparent';b.style.borderColor=on?'#18eda055':'transparent';b.style.color=on?'#b9ffe4':'#9f96ac'});const players=allPlayers();document.querySelectorAll('[data-player-id]').forEach(el=>{const p=players.get(Number(el.dataset.playerId));if(!p)return;const xp=el.querySelector('.xp');const fix=el.querySelector('.fix');if(xp){if(mode==='fixture')xp.innerHTML=fixtureStrip(p);else xp.textContent=viewValue(p,mode)}if(fix){fix.style.opacity=mode==='fixture'?'0':'1';fix.style.height=mode==='fixture'?'0':''}})}
  function squadViewSelector(){if(document.querySelector('#squadViewSelector'))return;const host=document.querySelector('#squadInsights')||document.querySelector('#current')?.closest('.section');if(!host)return;host.insertAdjacentHTML('afterend',`<div id="squadViewSelector" class="section" style="padding:7px;display:flex;gap:4px;overflow:auto"><button data-mode="xp">xP</button><button data-mode="fixture">3 GW</button><button data-mode="form">Form</button><button data-mode="risk">Risiko</button></div>`);document.querySelectorAll('#squadViewSelector button').forEach(b=>{b.style.cssText='flex:1;min-width:68px;padding:8px 9px;border-radius:11px;border:1px solid transparent;background:transparent;color:#9f96ac;font-size:10px;font-weight:900;white-space:nowrap';b.onclick=()=>applySquadView(b.dataset.mode)});setTimeout(()=>applySquadView(localStorage.getItem('fplSquadView')||'xp'),0)}
  function tagPitchPlayers(){const players=allPlayers();document.querySelectorAll('.player').forEach(el=>{if(el.dataset.playerId)return;const name=(el.querySelector('.name')?.textContent||'').trim();const p=[...players.values()].find(x=>String(x.name||'').trim()===name);if(p)el.dataset.playerId=p.id})}
  function renderBenches(){if(typeof D==='undefined'||!D)return;const curXi=(D.comparison||{}).current_xi||D.lineup||[];const afterXi=(D.comparison||{}).transfer_xi||D.lineup||curXi;const xs=changes();const active=[...(D.lineup||[]),...(D.bench||[])];const approved=Boolean(D.decision_layer?.approved_first_move);const currentSquad=approved?replacePlayers(active,'in','out',xs):active;const afterSquad=approved?active:replacePlayers(active,'out','in',xs);const currentBench=benchFrom(currentSquad,curXi);const afterBench=benchFrom(afterSquad,afterXi);const outIds=new Set(xs.map(x=>Number(x.out.id))),inIds=new Set(xs.map(x=>Number(x.in.id)));const health=squadHealth(currentSquad);const currentSection=document.querySelector('#current')?.closest('.section');if(currentSection){const h=currentSection.querySelector('h2');if(h)h.textContent='Siste bekreftede FPL-startellever';const old=document.querySelector('#fplSourceNote');if(old)old.remove();h?.insertAdjacentHTML('afterend',sourceNote(health));if(!document.querySelector('#currentBench'))currentSection.insertAdjacentHTML('afterend','<div class="section" id="currentBenchSection"><h2>Siste bekreftede FPL-benk</h2><div id="currentBench" class="bench"></div></div>')}const after=document.querySelector('#after')?.closest('.section')?.querySelector('h2');if(after)after.textContent='Modellens lag etter foreslått trekk';const oldBench=document.querySelector('#bench');if(oldBench){const h=oldBench.closest('.section')?.querySelector('h2');if(h)h.textContent='Modellens benk etter foreslått trekk'}const cb=document.querySelector('#currentBench');if(cb)cb.innerHTML=currentBench.map(p=>benchCard(p,outIds.has(Number(p.id))?'out':'')).join('');if(oldBench)oldBench.innerHTML=afterBench.map(p=>benchCard(p,inIds.has(Number(p.id))?'in':'')).join('')}
  function confidence(e){const s=e.confidence||{};return {score:Number.isFinite(Number(s.score))?Math.max(0,Math.min(100,Math.round(Number(s.score)))):50,level:['LAV','MIDDELS','HØY'].includes(s.level)?s.level:'LAV'}}
  function renderCaptain(){if(typeof D==='undefined'||!D||!D.captain_explanation)return;const e=D.captain_explanation,c=e.captain||{},r=e.runner_up||{},conf=confidence(e),host=document.querySelector('#captains');if(!host||document.querySelector('#captainExplain'))return;const box=document.createElement('div');box.id='captainExplain';box.style.cssText='grid-column:1/-1;margin-top:2px;padding:13px;border-radius:17px;border:1px solid #00e99044;background:linear-gradient(145deg,#00e9900d,#ffffff08)';const col=conf.level==='HØY'?'#00e990':conf.level==='MIDDELS'?'#ffd45b':'#ff7a92';box.innerHTML=`<div class="eyebrow">Hvorfor kaptein?</div><div style="display:flex;justify-content:space-between;gap:10px"><div><b style="font-size:20px">${c.name||'—'} (C)</b><div class="muted">${c.team||''} · modell ${e.model||'—'}</div></div><div style="text-align:right"><b>${num(c.xp)} xP</b><div class="muted">${num(c.expected_minutes,0)} min · ${pct(c.availability)}</div></div></div><div style="margin-top:10px;padding:10px;border-radius:13px;background:#0002"><div style="display:flex;justify-content:space-between"><b>${conf.level} confidence</b><b style="color:${col}">${conf.score}%</b></div><div style="height:7px;border-radius:99px;background:#ffffff12;margin-top:7px;overflow:hidden"><div style="height:100%;width:${conf.score}%;background:${col}"></div></div></div><div style="margin-top:9px;font-size:11px"><b>Mot #2 ${r.name||'—'}:</b> modellgap ${e.score_gap==null?'—':num(e.score_gap,3)} · xP-gap ${e.xp_gap==null?'—':num(e.xp_gap)}.</div>`;host.appendChild(box)}
  function polish(){const meta=document.querySelector('#meta');if(meta&&D?.source_snapshot_gw)meta.title='Siste offentlig bekreftede FPL-snapshot';document.querySelectorAll('.section h2').forEach(h=>h.style.letterSpacing='-.025em');deadlineBox();insightBar();tagPitchPlayers();squadViewSelector();applySquadView(localStorage.getItem('fplSquadView')||'xp')}
  function render(){renderCaptain();renderBenches();polish()}
  window.addEventListener('load',()=>{setTimeout(render,350);setTimeout(render,1200)});new MutationObserver(()=>render()).observe(document.documentElement,{childList:true,subtree:true});
})();
