(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function pcard(p){const tag=p.optimal_captain?' <span class="status do">C</span>':p.optimal_vice?' <span class="status consider">VC</span>':'';return `<div class="card" style="padding:10px;text-align:center;min-width:0"><b>${esc(p.name)}${tag}</b><div class="muted">${esc(p.team||'')} · ${esc(p.fixture||'')}</div><div style="margin-top:5px"><b>${Number(p.xp||0).toFixed(1)} p</b> <span class="muted">forventet</span></div>${p.news?`<div class="muted" style="margin-top:4px">${esc(p.news)}</div>`:''}</div>`}
function visualPlayers(rows){return (rows||[]).map(p=>({...p,captain:!!p.optimal_captain,vice:!!p.optimal_vice}))}
function renderVisualOptimal(d){const o=d.optimal_current_lineup||{};if(o.version!=='1.0-xp-legal-xi')return;const after=document.getElementById('after'),bench=document.getElementById('bench');if(after&&typeof pitch==='function')after.innerHTML=pitch(visualPlayers(o.lineup||[]));if(bench&&typeof benchHtml==='function')bench.innerHTML=benchHtml(visualPlayers(o.bench||[]));}
function lineupHtml(d){const o=d.optimal_current_lineup||{},cs=d.current_squad||{};if(o.version!=='1.0-xp-legal-xi'||!String(cs.version||'').startsWith('1.'))return'';const tx=Number(cs.transfer_count_current_gw||0),src=cs.predeadline_override_active?'Bruker ditt bekreftede pre-deadline-bytte til FPL offentliggjør transferhistorikken.':'Synket mot offisiell FPL-transferhistorikk.';return `<div class="section" id="optimalCurrentSection"><div class="tabExplain"><b>OPTIMAL XI = anbefalt lag akkurat nå</b><span>${esc(src)} Banen under viser den lovlige XI-en med høyest forventet GW-score.</span></div><div class="card"><div class="planrow"><div><div class="eyebrow">GW ${esc(o.gw)}</div><b>Formasjon ${esc(o.formation||'—')}</b></div><div style="text-align:right"><b>${Number(o.expected_team_score||0).toFixed(1)} forventede p</b><div class="muted">før kapteinsdobling</div></div></div><div class="miniStats" style="margin-top:9px"><div class="mini"><b>${esc(o.captain||'—')}</b><span>kaptein</span></div><div class="mini"><b>${esc(o.vice||'—')}</b><span>visekaptein</span></div><div class="mini"><b>${tx}</b><span>GW-transfers</span></div></div></div></div>`}
function postTransferHtml(d){const s=d.current_transfer_state||{},o=d.optimal_current_lineup||{};if(!s.post_transfer_mode)return'';const moves=(s.moves||[]).map(m=>`${esc(m.out_name)} → ${esc(m.in_name)}`).join(', ');return `<div class="section" id="postTransferSection"><div class="card"><div class="decisionTop"><div><div class="eyebrow">GW ${esc(s.gw)} · transfer gjennomført</div><div class="decisionWord" style="font-size:22px">NÅ: SETT OPTIMALT LAG</div></div><span class="badge go">${esc(s.free_transfers_remaining)} FT igjen</span></div><div class="trigger"><b>${moves||'Transfer registrert'}</b><br>Optimal XI er ${esc(o.formation||'—')} med ${Number(o.expected_team_score||0).toFixed(1)} forventede poeng, ${esc(o.captain||'—')} som kaptein og ${esc(o.vice||'—')} som visekaptein.</div></div></div>`}
function applyPostTransferMode(d){const s=d.current_transfer_state||{};if(!s.post_transfer_mode)return;const h=document.getElementById('headline'),sum=document.getElementById('summary');if(h)h.textContent='SETT OPTIMALT LAG';if(sum)sum.textContent='Ukens gratisbytte er brukt. Hovedfokus er nå startellever, kaptein, visekaptein og benkerekkefølge.';const old=document.getElementById('finalDuelSection');if(old)old.remove();const decision=document.getElementById('decision');if(decision&&!document.getElementById('postTransferSection'))decision.insertAdjacentHTML('afterbegin',postTransferHtml(d));}
async function run(){try{const r=await fetch(`data.json?lineup=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const d=await r.json(),team=document.getElementById('team');applyPostTransferMode(d);renderVisualOptimal(d);if(!team||document.getElementById('optimalCurrentSection'))return;const html=lineupHtml(d);if(!html)return;const note=document.getElementById('sourceNote');if(note)note.insertAdjacentHTML('afterend',html);else team.insertAdjacentHTML('afterbegin',html)}catch(_e){console.error('optimal lineup render failed',_e)}}
window.addEventListener('load',()=>setTimeout(run,250));
})();