(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmt=v=>{const n=Number(v);return Number.isFinite(n)?`${n>=0?'+':''}${n.toFixed(2)} p`:'—'};
const money=v=>{const n=Number(v);return Number.isFinite(n)?`£${n.toFixed(1)}m`:'—'};
const pct=v=>{const n=Number(v);return Number.isFinite(n)?`${Math.round(n*100)} %`:'—'};
function duelHtml(d){
 const duel=d.final_transfer_duel||{}; if(!String(duel.version||'').startsWith('2.'))return'';
 const verdict=duel.verdict||'—', confidence=Math.round(Number(duel.confidence||0)*100), fg=d.final_transfer_gate||{}, cands=d.candidates||[];
 const rows=(duel.rows||[]).map(r=>{
   const bank=r.kind==='bank', cover=r.bench_adjustment_applied&&r.bench_cover?`<div class="muted">Benkedekning: ${esc(r.bench_cover)} (${Number(r.bench_cover_expected||0).toFixed(1)} forventede p)</div>`:'';
   const necessity=!bank&&r.necessity?`<div class="planMeta" style="margin-top:6px"><b>Byttenødvendighet: ${esc(r.necessity)}</b>${Number.isFinite(Number(r.necessity_score))?` · score ${Number(r.necessity_score).toFixed(2)}`:''}</div>`:'';
   const cand=!bank&&r.rank?cands[Number(r.rank)-1]:null, regret=cand?.transfer_regret_shadow||{};
   const regretHtml=!bank&&regret.version?`<div class="why" style="margin-top:9px"><div class="eyebrow">Angrerisiko</div><div class="miniStats"><div class="mini"><b>${pct(regret.regret_make_transfer)}</b><span>risiko for å angre hvis vi gjør byttet</span></div><div class="mini"><b>${pct(regret.regret_save_ft)}</b><span>risiko for å angre hvis vi sparer FT</span></div></div><div class="planMeta" style="margin-top:7px"><b>${esc(regret.verdict||'')}</b></div></div>`:'';
   return `<article class="card" style="margin-top:8px"><div class="planrow"><div><div class="eyebrow">${bank?'BASELINE':`KANDIDAT #${r.rank}`}</div><b>${esc(r.label)}</b></div><span class="status ${bank?'consider':r.rank===1?'do':'consider'}">${bank?'SPAR FT':esc(r.status||'VURDERES')}</span></div>${cover}${necessity}<div class="stats"><div class="stat"><b>${fmt(r.next_gw_gain_after_bench)}</b><span>gevinst neste runde etter benk</span></div><div class="stat"><b>${fmt(r.three_gw_gain_after_bench)}</b><span>gevinst neste 3 runder</span></div><div class="stat"><b>${fmt(r.plan_gain_after_bench)}</b><span>gevinst i planhorisonten</span></div></div><div class="planMeta" style="margin-top:8px">Robusthet: ${esc(r.robustness||'—')} · Timing: ${esc(r.timing||'—')} · Bank etter: ${money(r.bank_after)}</div>${regretHtml}</article>`;
 }).join('');
 const warnings=[...(duel.blockers||[]),...(duel.warnings||[])], triggers=fg.go_triggers||[], rechecks=fg.recheck_conditions||[];
 return `<div class="section" id="finalDuelSection"><h2>Siste transferduell</h2><div class="card"><div class="decisionTop"><div><div class="eyebrow">#1 vs #2 vs spar gratisbyttet</div><div class="decisionWord" style="font-size:22px">${esc(verdict)}</div></div><span class="badge ${verdict==='GO'?'go':'bank'}">${confidence}% sikkerhet</span></div><div class="muted" style="margin-top:7px">Benkekorrigert og nødvendighetsjustert sammenligning. Angrerisiko viser hvilken side av beslutningen som er farligst dersom prognosen tar feil.</div>${fg.necessity_label?`<div class="trigger"><b>Byttenødvendighet: ${esc(fg.necessity_label)}</b><br>${esc(fg.next_action||'')}</div>`:''}${warnings.length?`<div class="why" style="margin-top:9px"><div class="eyebrow">Hvorfor er vi forsiktige?</div>${warnings.map(x=>`<div class="whyItem">${esc(x)}</div>`).join('')}</div>`:''}${triggers.length?`<div class="why" style="margin-top:9px"><div class="eyebrow">Hva må til for GO?</div>${triggers.map(x=>`<div class="whyItem">${esc(x)}</div>`).join('')}</div>`:''}${rechecks.length?`<div class="why" style="margin-top:9px"><div class="eyebrow">Sjekk igjen før deadline</div>${rechecks.map(x=>`<div class="whyItem">${esc(x)}</div>`).join('')}</div>`:''}</div>${rows}</div>`;
}
function planCard(x){
 const a=x.action||{},pi=x.plan_intelligence||{},score=Number(x.xi_xp||pi.expected_team_score||0),bankBefore=Number(pi.bank_before),bankAfter=Number(pi.bank_after),hit=Number(a.hit||0);
 const pairs=(a.pairs||[]).map(p=>`<div class="move"><div class="swap outSwap"><b>${esc((p.out||{}).name||'?')}</b><div class="muted">UT · ${esc((p.out||{}).team||'')}</div></div><div class="arrow">→</div><div class="swap inSwap"><b>${esc((p.in||{}).name||'?')}</b><div class="muted">INN · ${esc((p.in||{}).team||'')}</div></div></div>`).join('');
 const why=(pi.why||[]).map(v=>`<div class="whyItem">${esc(v)}</div>`).join('');
 const trig=(pi.change_triggers||[]).map(v=>`<div class="whyItem">${esc(v)}</div>`).join('');
 return `<article class="card"><div class="planrow"><div><div class="eyebrow">Runde ${esc(x.gw)}</div><b>${esc(a.label||'Spar gratisbyttet')}</b></div><div style="text-align:right"><b>Forventet lagscore: ${score.toFixed(1)} p</b><div class="muted">for startelleveren denne runden</div></div></div>${pairs}<div class="miniStats"><div class="mini"><b>${esc(pi.free_transfers_before??'—')} → ${esc(pi.free_transfers_after??'—')}</b><span>gratisbytter før → etter</span></div><div class="mini"><b>${money(bankBefore)} → ${money(bankAfter)}</b><span>bank før → etter</span></div><div class="mini"><b>${hit?`-${hit} p`:'0 p'}</b><span>poengkostnad</span></div></div><div class="planMeta" style="margin-top:9px">Kaptein: ${esc(x.captain||'—')} · Plansikkerhet: ${esc(pi.confidence||'—')}</div>${why?`<div class="why" style="margin-top:9px"><div class="eyebrow">Hvorfor ligger dette i planen?</div>${why}</div>`:''}${trig?`<div class="why" style="margin-top:9px"><div class="eyebrow">Hva kan endre planen?</div>${trig}</div>`:''}<div class="trigger"><b>Rullerende plan</b><br>${esc(pi.note||'Planen bygges på nytt når ferske data kommer.')}</div></article>`;
}
async function run(){try{
 const r=await fetch(`data.json?meta=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const d=await r.json();
 const el=document.getElementById('teamId');if(el)el.textContent=d.fpl_team_id?`FPL-lag #${d.fpl_team_id}`:'FPL-lag: ikke tilgjengelig';
 const decision=document.getElementById('decision'); if(decision&&!document.getElementById('finalDuelSection')){const html=duelHtml(d);if(html)decision.insertAdjacentHTML('afterbegin',html)}
 const future=document.getElementById('future');if(future&&(d.future||[]).some(x=>x.plan_intelligence)){future.innerHTML=(d.future||[]).map(planCard).join('')}
}catch(_e){}}
run();
})();