(()=>{
const e=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pct=v=>Number.isFinite(Number(v))?`${Math.round(Number(v)*100)} %`:'—';
function chosen(d){return d.action_package_selection?.selected||{kind:'bank',label:'SPAR GRATISBYTTET',pairs:[]}}
function moveLabel(_d,c){return c?.label||(c?.pairs||[]).map(x=>`${x.out?.name||'—'} → ${x.in?.name||'—'}`).join(' + ')||'SPAR GRATISBYTTET'}
async function run(){try{
 const r=await fetch(`data.json?focus=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const d=await r.json(),gate=d.final_transfer_gate||{},lock=d.deadline_lock?.verdict,verdict=lock==='UNLOCKED / GO'?'GO':lock==='UNLOCKED ONLY AFTER RECHECK'?'WAIT / RECHECK':lock==='LOCKED / NO-GO'?'NO-GO':gate.verdict||'NO-GO',c=chosen(d),row=c,ft=Number(d.current_transfer_state?.free_transfers_remaining??d.free_transfers_assumed??0),next=Number(c.free_transfers_next_gw??Math.min(5,ft+1)),move=moveLabel(d,c),go=verdict==='GO'&&c.kind!=='bank',wait=verdict==='WAIT / RECHECK';
 const summary=document.getElementById('summary');if(summary)summary.textContent=go?`Gjør bare ${move}. Trekket er godkjent på tvers av poeng, spilletid, benk og fleksibilitet.`:wait?`Ikke gjør byttet ennå. ${move} er pakken vi følger, men mer informasjon er verdt mer enn å handle tidlig.`:(c.kind==='bank'?'Spar gratisbyttet. Det rangeres høyest på den felles sammenligningen.':`Spar gratisbyttet nå. ${move} rangeres høyest, men har ikke passert sikkerhetskontrollen.`);
 const box=document.getElementById('decisionBox');if(!box)return;const advanced=box.innerHTML,word=go?`GJØR ${move}`:wait?'VENT – IKKE BYTT':'SPAR GRATISBYTTET',badge=go?'GODKJENT':wait?'NY SJEKK':'AKTIVT VALG',cls=go?'go':wait?'consider':'weak',gain=Number(row.three_gw_gain_after_cost);
 const shownGain=Number.isFinite(gain)?`${gain>=0?'+':''}${gain.toFixed(1)} p`:'—',reason=go?'Pakken slår å spare også etter benk, risiko og eventuell poengkostnad.':wait?'Dette er beste pakke på felles sammenligning, men den må sjekkes igjen før du handler.':(c.kind==='bank'?'Å spare rangeres høyest når poeng, kostnad og fleksibilitet vurderes samlet.':'Sikkerhetskontrollen godkjenner ikke pakken nå; derfor er handlingen å spare.');
 box.innerHTML=`<article class="decisionFocus"><div class="focusTop"><div><div class="eyebrow">Ditt valg nå</div><div class="focusWord">${e(word)}</div></div><span class="badge ${cls}">${e(badge)}</span></div><p>${e(reason)}</p><div class="focusMetrics"><div><b>${shownGain}</b><span>3 runder etter kostnad</span></div><div><b>${pct(row.reliability??gate.confidence)}</b><span>pålitelighet</span></div><div><b>${Number(c.hit||0)} p</b><span>byttehit</span></div></div>${!go&&c.kind!=='bank'?`<div class="watchMove"><span>Beste pakke vi følger</span><b>${e(move)}</b></div>`:''}</article><details class="modelDetails"><summary>Se sammenligningen og sikkerhetskontrollen</summary>${advanced}</details>`;
 }catch(_e){}}
window.addEventListener('load',()=>setTimeout(run,700));
})();
